In [14]:
import pandas as pd
import numpy as np
df=pd.read_csv('youtube_all_region.csv')
df.drop_duplicates(subset='video_id', keep='first', inplace=True)
df

,video_id,title,channel,channel_id,published,views,likes,thumbnail_url,category_id,subscribers,region,Source.Name
0,F8ZTXYOPRZ4,Do your baby’s hair 🤣#greys #greysanatomy #fyp,Andy Huang,UCy06srAhwzLdsPBC6CiR96A,2025-02-18T06:00:09Z,7378507,438016,https://i.ytimg.com/vi/F8ZTXYOPRZ4/hqdefault.jpg,22,16000,CA,NaN
1,bZVQcBgjfSI,XYL ARP556+Black Bear Tracer.Who needs this fo...,LKCJ,UC_bPnE6C8ucaq7JHPKlaf-Q,2025-02-25T14:50:30Z,2550039,65566,https://i.ytimg.com/vi/bZVQcBgjfSI/hqdefault.jpg,22,5680000,CA,NaN
2,WPc3qG3kZnw,How to terminate a Cat7 field termination with...,HY CONNECT,UCYxXK5KWL_Ta6jZ4yzFGVhQ,2025-02-13T08:33:21Z,1989137,22551,https://i.ytimg.com/vi/WPc3qG3kZnw/hqdefault.jpg,22,12800,CA,NaN
3,mvWE3inpe6Y,"If you want to eat chicken wings, you can try ...",Chinese Cuisine Official channel,UCY6zyw7X3tMYAN5ZxbrNyog,2025-02-11T12:01:13Z,173074,3513,https://i.ytimg.com/vi/mvWE3inpe6Y/hqdefault.jpg,26,67000,CA,NaN
4,mle65DevJQo,Peppa Pig’s New Red Bed | Kids Story Animation,Mushroom,UCcYKDKMq3KMxcpdF9bteFFQ,2025-02-12T04:00:28Z,13451466,585370,https://i.ytimg.com/vi/mle65DevJQo/hqdefault.jpg,1,4600000,CA,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
12569,3DmX7mEp2gY,"Ammayi Garu - Quick Recap - 4 - Apuroopa, Raju...",Zee Telugu,UC3PYGKK29qJ0zu-eEthHK4g,2025-02-22T03:10:00Z,1377,12,https://i.ytimg.com/vi/3DmX7mEp2gY/hqdefault.jpg,24,16600000,IND,NaN
12570,IHvJWhQhjos,Nindu Noorella Saavasam - Quick Recap - 11 - M...,Zee Telugu,UC3PYGKK29qJ0zu-eEthHK4g,2025-02-24T03:20:00Z,2236,31,https://i.ytimg.com/vi/IHvJWhQhjos/hqdefault.jpg,24,16600000,IND,NaN
12571,2R3fRhGFdIw,Meenakshi Ponnunga - Quick Recap - 26 - Meenak...,Zee Tamil,UC_wIGmvdyAQLtl-U2nHV9rg,2025-02-23T06:00:02Z,676,3,https://i.ytimg.com/vi/2R3fRhGFdIw/hqdefault.jpg,24,16400000,IND,NaN
12572,Adpmxe2Us4Y,Meenakshi Ponnunga - Quick Recap - 15 - Meenak...,Zee Tamil,UC_wIGmvdyAQLtl-U2nHV9rg,2025-02-22T06:00:11Z,407,2,https://i.ytimg.com/vi/Adpmxe2Us4Y/hqdefault.jpg,24,16400000,IND,NaN
12573,_1qOJ5mw3xg,"Prema Entha Maduram - Quick Recap - 17 - Anu, ...",Zee Telugu,UC3PYGKK29qJ0zu-eEthHK4g,2025-02-23T07:20:00Z,1629,25,https://i.ytimg.com/vi/_1qOJ5mw3xg/hqdefault.jpg,24,16600000,IND,NaN

In [3]:
!pip install requests tqdm

Requirement already satisfied: requests in /opt/conda/lib/python3.10/site-packages (2.32.3)
Requirement already satisfied: tqdm in /opt/conda/lib/python3.10/site-packages (4.67.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/conda/lib/python3.10/site-packages (from requests) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.10/site-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.10/site-packages (from requests) (1.26.20)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.10/site-packages (from requests) (2024.12.14)

[notice] A new release of pip is available: 25.0 -> 25.0.1
[notice] To update, run: pip install --upgrade pip

In [4]:
import os
import requests
from tqdm import tqdm

# 设置保存路径
save_path = '/home/jupyter/youtube_thumbnails'
os.makedirs(save_path, exist_ok=True)

# 定义下载函数
def download_thumbnail(video_id, url):
    try:
        file_path = os.path.join(save_path, f"{video_id}.jpg")
        if os.path.exists(file_path):
            return  # 避免重复下载
        response = requests.get(url, timeout=10)
        if response.status_code == 200:
            with open(file_path, 'wb') as f:
                f.write(response.content)
        else:
            print(f"❌ {video_id} 下载失败，状态码: {response.status_code}")
    except Exception as e:
        print(f"⚠️ {video_id} 下载异常: {e}")

# 遍历 DataFrame 下载缩略图
for _, row in tqdm(df.iterrows(), total=len(df)):
    video_id = str(row['video_id'])
    url = row['thumbnail_url']
    download_thumbnail(video_id, url)

print("✅ 全部封面图已下载完毕。")

  1%|          | 133/12574 [00:04<05:41, 36.47it/s]

❌ 1FzQh1lEhw4 下载失败，状态码: 404

  7%|▋         | 901/12574 [00:30<07:55, 24.56it/s]

❌ C0XpNEWYj3g 下载失败，状态码: 404

 48%|████▊     | 6004/12574 [02:25<02:11, 49.88it/s]

❌ 1FzQh1lEhw4 下载失败，状态码: 404

 50%|████▉     | 6272/12574 [02:31<02:19, 45.22it/s]

❌ j1PUSdC_KiE 下载失败，状态码: 404

 54%|█████▍    | 6813/12574 [02:41<01:36, 59.68it/s]

❌ C0XpNEWYj3g 下载失败，状态码: 404

 68%|██████▊   | 8529/12574 [03:12<01:08, 58.73it/s]

❌ afO7r8TQTSw 下载失败，状态码: 404

 71%|███████   | 8921/12574 [03:19<01:09, 52.67it/s]

❌ 1FzQh1lEhw4 下载失败，状态码: 404

 71%|███████   | 8940/12574 [03:19<01:02, 58.28it/s]

❌ kEFsJIyxMu8 下载失败，状态码: 404

 72%|███████▏  | 9002/12574 [03:20<01:27, 40.97it/s]

❌ gHA61-ZOCZM 下载失败，状态码: 404

 73%|███████▎  | 9211/12574 [03:29<02:12, 25.40it/s]

❌ jyPri45ijXM 下载失败，状态码: 404

 73%|███████▎  | 9220/12574 [03:29<01:52, 29.87it/s]

❌ 5m2fSr1JmAs 下载失败，状态码: 404

 74%|███████▍  | 9281/12574 [03:31<01:34, 34.81it/s]

❌ un-5Yird5lk 下载失败，状态码: 404

 74%|███████▍  | 9355/12574 [03:33<01:31, 35.09it/s]

❌ KcPB0kZcIoU 下载失败，状态码: 404

 75%|███████▍  | 9380/12574 [03:34<01:53, 28.14it/s]

❌ 0d0S6FlP87Y 下载失败，状态码: 404

 75%|███████▍  | 9394/12574 [03:35<01:56, 27.37it/s]

❌ 7oN9p52Crz0 下载失败，状态码: 404

 75%|███████▍  | 9403/12574 [03:35<01:43, 30.56it/s]

❌ odtgjYKt9IQ 下载失败，状态码: 404
❌ fmm4OzLVTfs 下载失败，状态码: 404

 75%|███████▍  | 9410/12574 [03:35<02:01, 25.94it/s]

❌ E5KwPgdlpNg 下载失败，状态码: 404

 75%|███████▌  | 9456/12574 [03:37<02:23, 21.74it/s]

❌ jYcEyV861Dk 下载失败，状态码: 404

 76%|███████▌  | 9501/12574 [03:39<02:04, 24.64it/s]

❌ nT9Bd8esqKs 下载失败，状态码: 404

 76%|███████▌  | 9526/12574 [03:39<01:19, 38.22it/s]

❌ MHjPwfDHY_s 下载失败，状态码: 404

 76%|███████▋  | 9588/12574 [03:42<01:48, 27.41it/s]

❌ qwhA23GJ4KU 下载失败，状态码: 404

 77%|███████▋  | 9719/12574 [03:46<01:45, 26.95it/s]

❌ F41JBdXmlns 下载失败，状态码: 404

 81%|████████  | 10145/12574 [03:57<00:47, 50.63it/s]

❌ OOvvd9THX68 下载失败，状态码: 404

 81%|████████  | 10170/12574 [03:57<00:43, 55.77it/s]

❌ JWOGawBclDo 下载失败，状态码: 404

 82%|████████▏ | 10253/12574 [03:59<00:43, 53.15it/s]

❌ uCewsWVpkWQ 下载失败，状态码: 404

 87%|████████▋ | 10924/12574 [04:17<00:53, 30.92it/s]

❌ dBw0xcjGY_I 下载失败，状态码: 404

 96%|█████████▌| 12011/12574 [04:39<00:13, 42.69it/s]

❌ 1FzQh1lEhw4 下载失败，状态码: 404

100%|██████████| 12574/12574 [04:52<00:00, 42.99it/s]

✅ 全部封面图已下载完毕。

In [8]:
import os

folder_path = 'youtube_thumbnails'  # 用引号表示是字符串路径
files = os.listdir(folder_path)
image_count = len([f for f in files if f.endswith('.jpg')])

print(f"✅ 一共成功下载了 {image_count} 张图片！🎉")

✅ 一共成功下载了 11731 张图片！🎉

In [9]:
# 提取失败图片的 video_id 列表
import os

# 所有的 video_id
all_video_ids = set(df['video_id'])

# 下载成功的图片名（去掉 .jpg 后缀）
downloaded = set([f.split('.')[0] for f in os.listdir('youtube_thumbnails') if f.endswith('.jpg')])

# 失败的 video_id
failed = all_video_ids - downloaded
for vid in failed:
    print(vid)

dBw0xcjGY_I
jyPri45ijXM
afO7r8TQTSw
E5KwPgdlpNg
KcPB0kZcIoU
uCewsWVpkWQ
gHA61-ZOCZM
un-5Yird5lk
7oN9p52Crz0
MHjPwfDHY_s
1FzQh1lEhw4
jYcEyV861Dk
0d0S6FlP87Y
5m2fSr1JmAs
qwhA23GJ4KU
odtgjYKt9IQ
JWOGawBclDo
C0XpNEWYj3g
F41JBdXmlns
fmm4OzLVTfs
j1PUSdC_KiE
nT9Bd8esqKs
OOvvd9THX68
kEFsJIyxMu8

In [15]:
# 将失败的 video_id 从 DataFrame 中去掉
df_cleaned = df[~df['video_id'].isin(failed)]
df_cleaned

,video_id,title,channel,channel_id,published,views,likes,thumbnail_url,category_id,subscribers,region,Source.Name
0,F8ZTXYOPRZ4,Do your baby’s hair 🤣#greys #greysanatomy #fyp,Andy Huang,UCy06srAhwzLdsPBC6CiR96A,2025-02-18T06:00:09Z,7378507,438016,https://i.ytimg.com/vi/F8ZTXYOPRZ4/hqdefault.jpg,22,16000,CA,NaN
1,bZVQcBgjfSI,XYL ARP556+Black Bear Tracer.Who needs this fo...,LKCJ,UC_bPnE6C8ucaq7JHPKlaf-Q,2025-02-25T14:50:30Z,2550039,65566,https://i.ytimg.com/vi/bZVQcBgjfSI/hqdefault.jpg,22,5680000,CA,NaN
2,WPc3qG3kZnw,How to terminate a Cat7 field termination with...,HY CONNECT,UCYxXK5KWL_Ta6jZ4yzFGVhQ,2025-02-13T08:33:21Z,1989137,22551,https://i.ytimg.com/vi/WPc3qG3kZnw/hqdefault.jpg,22,12800,CA,NaN
3,mvWE3inpe6Y,"If you want to eat chicken wings, you can try ...",Chinese Cuisine Official channel,UCY6zyw7X3tMYAN5ZxbrNyog,2025-02-11T12:01:13Z,173074,3513,https://i.ytimg.com/vi/mvWE3inpe6Y/hqdefault.jpg,26,67000,CA,NaN
4,mle65DevJQo,Peppa Pig’s New Red Bed | Kids Story Animation,Mushroom,UCcYKDKMq3KMxcpdF9bteFFQ,2025-02-12T04:00:28Z,13451466,585370,https://i.ytimg.com/vi/mle65DevJQo/hqdefault.jpg,1,4600000,CA,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
12569,3DmX7mEp2gY,"Ammayi Garu - Quick Recap - 4 - Apuroopa, Raju...",Zee Telugu,UC3PYGKK29qJ0zu-eEthHK4g,2025-02-22T03:10:00Z,1377,12,https://i.ytimg.com/vi/3DmX7mEp2gY/hqdefault.jpg,24,16600000,IND,NaN
12570,IHvJWhQhjos,Nindu Noorella Saavasam - Quick Recap - 11 - M...,Zee Telugu,UC3PYGKK29qJ0zu-eEthHK4g,2025-02-24T03:20:00Z,2236,31,https://i.ytimg.com/vi/IHvJWhQhjos/hqdefault.jpg,24,16600000,IND,NaN
12571,2R3fRhGFdIw,Meenakshi Ponnunga - Quick Recap - 26 - Meenak...,Zee Tamil,UC_wIGmvdyAQLtl-U2nHV9rg,2025-02-23T06:00:02Z,676,3,https://i.ytimg.com/vi/2R3fRhGFdIw/hqdefault.jpg,24,16400000,IND,NaN
12572,Adpmxe2Us4Y,Meenakshi Ponnunga - Quick Recap - 15 - Meenak...,Zee Tamil,UC_wIGmvdyAQLtl-U2nHV9rg,2025-02-22T06:00:11Z,407,2,https://i.ytimg.com/vi/Adpmxe2Us4Y/hqdefault.jpg,24,16400000,IND,NaN
12573,_1qOJ5mw3xg,"Prema Entha Maduram - Quick Recap - 17 - Anu, ...",Zee Telugu,UC3PYGKK29qJ0zu-eEthHK4g,2025-02-23T07:20:00Z,1629,25,https://i.ytimg.com/vi/_1qOJ5mw3xg/hqdefault.jpg,24,16600000,IND,NaN

In [16]:
df_cleaned.to_csv('youtube_cleaned_success_only.csv', index=False)

In [2]:
df = pd.read_csv('youtube_cleaned_success_only.csv')

NameError: name 'pd' is not defined

In [ ]:
df['published'] = pd.to_datetime(df['published'], format="%Y-%m-%dT%H:%M:%SZ", errors='coerce')
df['publish_date'] = df['published'].dt.date
df['publish_time'] = df['published'].dt.time
df.drop('Source.Name',axis=1,inplace=True)
df.drop('published',axis=1,inplace=True)
df